export const userCartProjection = {
    "phone": 0,
    "_id": 0,
    "address": 0,
    "birthday": 0,
    "createdAt": 0,
    "email": 0,
    "family": 0,
    "favoriteFood": 0,
    "hashRT": 0,
    "image": 0,
    "name": 0,
    "otp": 0,
    "updatedAt": 0,
    "username": 0,
    "comments": 0,
    "imageUrl": 0,
    "role": 0,
    "carts.foodDetails.comments": 0,
    "carts.foodDetails.ingredients": 0,
    "carts.foodDetails.description": 0,
    "carts.foodDetails.category": 0,
    "carts.foodDetails.images": 0,
    "carts.foodDetails.subCategory": 0,
    "carts.foodDetails.rateCount": 0,
    "carts.foodDetail.foodId": 0
}